# Introduction

This is a book created from markdown and executable code.

<!-- PXL_20231119_164825569.NIGHT.jpg -->

| Base Quantity| Base Unit | Symbol|
|-----|-------|-----|
| length | meter | $m$|
|time| second| $s$|
|mass | kilogram | kg|
| electric current| ampere| A|
|Thermodynamic temperature | Kelvin | K|
| Amount of substance| mole| mol|
| Luminous Intensity| candela| cd|

: SI units  {.striped .hover}

|length|time|mass|charge|temperature|
|:--:|:--:|:--:|:--:|:--:|
|m|s|kg|C|K|

: Fundamental Units  {.striped .hover}

|Concept| Units|
|:--|:--|
|Force| $kg\; m\; s^{-2} = N$|
|Energy| $kg\; m^{2}\; s^{-2} = N\; m = J$|
|Power| $kg\; m^{2}\; s^{-3} = J\; s^{-1} = W$|
|Current| $C\; s^{-1}$|

: Combinations {.striped .hover}

Dimensional analysis: always checking and fudging (?).

Same units go to the same side of the equation! 

Vectors vs scalars

Math is a tool, not the be all and end all -- don't simply formula fit. 

Sensible answers! Check!

## Solving Problems with the 7D's and the little S

- Diagram: Big! (2/3 of a page) and as many as you need. Graphs
- Directions: Mark it (negative/positive)
- Definitions & Data: Put it on the page (all of them)
- Diagnosis: Type (how) conservation principles, force laws, angular momentum.
- Derivation: Equations (diagnosis in symbols) as many equations as variables add to diagram dimensions
- Determination - D'algebra - box the answer.
- Dimensions - Check and limiting cases -- if makes sense then possibly right (if not prob wrong). LHS = RHS then :grinning:.
- Substitution: if necessary - do rough calc by hand an dunits include error!



We can cite easily as well, see @knuth84 for additional discussion of literate programming.

